//
//  BibleMetadata.swift
//  TextMemoriser
//
//  Created by Cormell, David - DPC on 11/03/2024.
//
//numberOfVerses function generated by chatGPT on 11/03/2024
//https://chat.openai.com/share/8a0d3cc5-fc93-4f5d-bb20-c136970d81e9

import Foundation

class BibleMetadata {
    func numberOfVerses(in book: Book, chapter: Int) -> Int {
        switch book {
        case .Genesis:
            switch chapter {
            case 1: return 31
            case 2: return 25
            case 3: return 24
            case 4: return 26
            case 5: return 32
            case 6: return 22
            case 7: return 24
            case 8: return 22
            case 9: return 29
            case 10: return 32
            case 11: return 32
            case 12: return 20
            case 13: return 18
            case 14: return 24
            case 15: return 21
            case 16: return 16
            case 17: return 27
            case 18: return 33
            case 19: return 38
            case 20: return 18
            case 21: return 34
            case 22: return 24
            case 23: return 20
            case 24: return 67
            case 25: return 34
            case 26: return 35
            case 27: return 46
            case 28: return 22
            case 29: return 35
            case 30: return 43
            case 31: return 55
            case 32: return 32
            case 33: return 20
            case 34: return 31
            case 35: return 29
            case 36: return 43
            case 37: return 36
            case 38: return 30
            case 39: return 23
            case 40: return 23
            case 41: return 57
            case 42: return 38
            case 43: return 34
            case 44: return 34
            case 45: return 28
            case 46: return 34
            case 47: return 31
            case 48: return 22
            case 49: return 33
            case 50: return 26
            default: return 1
            }
        case .Exodus:
            switch chapter {
            case 1: return 22
            case 2: return 25
            case 3: return 22
            case 4: return 31
            case 5: return 23
            case 6: return 30
            case 7: return 25
            case 8: return 32
            case 9: return 35
            case 10: return 29
            case 11: return 10
            case 12: return 51
            case 13: return 22
            case 14: return 31
            case 15: return 27
            case 16: return 36
            case 17: return 16
            case 18: return 27
            case 19: return 25
            case 20: return 26
            case 21: return 36
            case 22: return 31
            case 23: return 33
            case 24: return 18
            case 25: return 40
            case 26: return 37
            case 27: return 21
            case 28: return 43
            case 29: return 46
            case 30: return 38
            case 31: return 18
            case 32: return 35
            case 33: return 23
            case 34: return 35
            case 35: return 35
            case 36: return 38
            case 37: return 29
            case 38: return 31
            case 39: return 43
            case 40: return 38
            default: return 1
            }
        case .Leviticus:
            switch chapter {
            case 1: return 17
            case 2: return 16
            case 3: return 17
            case 4: return 35
            case 5: return 19
            case 6: return 30
            case 7: return 38
            case 8: return 36
            case 9: return 24
            case 10: return 20
            case 11: return 47
            case 12: return 8
            case 13: return 59
            case 14: return 57
            case 15: return 33
            case 16: return 34
            case 17: return 16
            case 18: return 30
            case 19: return 37
            case 20: return 27
            case 21: return 24
            default: return 1
            }
        case .Numbers:
            switch chapter {
            case 1: return 54
            case 2: return 34
            case 3: return 51
            case 4: return 49
            case 5: return 31
            case 6: return 27
            case 7: return 89
            case 8: return 26
            case 9: return 23
            case 10: return 36
            case 11: return 35
            case 12: return 16
            case 13: return 33
            case 14: return 45
            case 15: return 41
            case 16: return 50
            case 17: return 13
            case 18: return 32
            case 19: return 22
            case 20: return 29
            case 21: return 35
            case 22: return 41
            case 23: return 30
            case 24: return 25
            case 25: return 18
            case 26: return 65
            case 27: return 23
            case 28: return 31
            case 29: return 39
            case 30: return 17
            case 31: return 54
            case 32: return 42
            case 33: return 56
            case 34: return 29
            case 35: return 34
            case 36: return 13
            default: return 1
            }
        case .Deuteronomy:
            switch chapter {
            case 1: return 46
            case 2: return 37
            case 3: return 29
            case 4: return 49
            case 5: return 33
            case 6: return 25
            case 7: return 26
            case 8: return 20
            case 9: return 29
            case 10: return 22
            case 11: return 32
            case 12: return 32
            case 13: return 18
            case 14: return 29
            case 15: return 23
            case 16: return 22
            case 17: return 20
            case 18: return 22
            case 19: return 21
            case 20: return 20
            case 21: return 23
            case 22: return 30
            case 23: return 25
            case 24: return 22
            case 25: return 19
            case 26: return 19
            case 27: return 26
            case 28: return 69
            case 29: return 28
            case 30: return 20
            case 31: return 30
            case 32: return 52
            case 33: return 29
            case 34: return 12
            default: return 1
            }
        case .Joshua:
            switch chapter {
            case 1: return 18
            case 2: return 24
            case 3: return 17
            case 4: return 24
            case 5: return 15
            case 6: return 27
            case 7: return 26
            case 8: return 35
            case 9: return 27
            case 10: return 43
            case 11: return 23
            case 12: return 24
            case 13: return 33
            case 14: return 15
            case 15: return 63
            case 16: return 10
            case 17: return 18
            case 18: return 28
            case 19: return 51
            case 20: return 9
            case 21: return 45
            case 22: return 34
            case 23: return 16
            case 24: return 33
            default: return 1
            }
        case .Judges:
            switch chapter {
            case 1: return 36
            case 2: return 23
            case 3: return 31
            case 4: return 24
            case 5: return 31
            case 6: return 40
            case 7: return 25
            case 8: return 35
            case 9: return 57
            case 10: return 18
            case 11: return 40
            case 12: return 15
            case 13: return 25
            case 14: return 20
            case 15: return 20
            case 16: return 31
            case 17: return 13
            case 18: return 31
            case 19: return 30
            case 20: return 48
            case 21: return 25
            default: return 1
            }
        case .Ruth:
            switch chapter {
            case 1: return 22
            case 2: return 23
            case 3: return 18
            case 4: return 22
            default: return 1
            }
        case .Samuel1:
            switch chapter {
            case 1: return 28
            case 2: return 36
            case 3: return 21
            case 4: return 22
            case 5: return 12
            case 6: return 21
            case 7: return 17
            case 8: return 22
            case 9: return 27
            case 10: return 27
            case 11: return 15
            case 12: return 25
            case 13: return 23
            case 14: return 52
            case 15: return 35
            case 16: return 23
            case 17: return 58
            case 18: return 30
            case 19: return 24
            case 20: return 42
            case 21: return 15
            default: return 1
            }
        case .Samuel2:
            switch chapter {
            case 1: return 27
            case 2: return 32
            case 3: return 39
            case 4: return 12
            case 5: return 25
            case 6: return 23
            case 7: return 29
            case 8: return 18
            case 9: return 13
            case 10: return 19
            case 11: return 27
            case 12: return 31
            case 13: return 39
            case 14: return 33
            case 15: return 37
            case 16: return 23
            case 17: return 29
            case 18: return 33
            case 19: return 43
            case 20: return 26
            case 21: return 22
            default: return 1
            }
        case .Kings1:
            switch chapter {
            case 1: return 53
            case 2: return 46
            case 3: return 28
            case 4: return 34
            case 5: return 18
            case 6: return 38
            case 7: return 51
            case 8: return 66
            case 9: return 28
            case 10: return 29
            case 11: return 43
            case 12: return 33
            case 13: return 34
            case 14: return 31
            case 15: return 34
            case 16: return 34
            case 17: return 24
            case 18: return 46
            case 19: return 21
            case 20: return 43
            case 21: return 29
            default: return 1
            }
        case .Kings2:
            switch chapter {
            case 1: return 18
            case 2: return 25
            case 3: return 27
            case 4: return 44
            case 5: return 27
            case 6: return 33
            case 7: return 20
            case 8: return 29
            case 9: return 37
            case 10: return 36
            case 11: return 21
            case 12: return 21
            case 13: return 25
            case 14: return 29
            case 15: return 38
            case 16: return 20
            case 17: return 41
            case 18: return 37
            case 19: return 37
            case 20: return 21
            case 21: return 26
            case 22: return 20
            case 23: return 37
            case 24: return 20
            case 25: return 30
            case 26: return 25
            case 27: return 32
            case 28: return 44
            case 29: return 30
            case 30: return 54
            case 31: return 46
            case 32: return 34
            case 33: return 34
            case 34: return 20
            case 35: return 28
            case 36: return 27
            case 37: return 31
            case 38: return 37
            case 39: return 37
            case 40: return 21
            default: return 1
            }
        case .Chronicles1:
            switch chapter {
            case 1: return 54
            case 2: return 55
            case 3: return 24
            case 4: return 43
            case 5: return 26
            case 6: return 81
            case 7: return 40
            case 8: return 40
            case 9: return 44
            case 10: return 14
            case 11: return 47
            case 12: return 40
            case 13: return 14
            case 14: return 17
            case 15: return 29
            case 16: return 43
            case 17: return 27
            case 18: return 17
            case 19: return 19
            case 20: return 8
            case 21: return 30
            case 22: return 19
            case 23: return 32
            case 24: return 31
            case 25: return 31
            case 26: return 32
            case 27: return 34
            case 28: return 21
            case 29: return 30
            case 30: return 54
            case 31: return 32
            case 32: return 23
            case 33: return 23
            case 34: return 33
            case 35: return 27
            case 36: return 20
            default: return 1
            }
        case .Chronicles2:
            switch chapter {
            case 1: return 17
            case 2: return 18
            case 3: return 17
            case 4: return 22
            case 5: return 14
            case 6: return 42
            case 7: return 22
            case 8: return 18
            case 9: return 31
            case 10: return 19
            case 11: return 23
            case 12: return 16
            case 13: return 22
            case 14: return 15
            case 15: return 19
            case 16: return 14
            case 17: return 19
            case 18: return 34
            case 19: return 11
            case 20: return 37
            case 21: return 20
            case 22: return 12
            case 23: return 21
            case 24: return 27
            case 25: return 28
            case 26: return 23
            case 27: return 9
            case 28: return 27
            case 29: return 36
            case 30: return 27
            case 31: return 21
            case 32: return 33
            case 33: return 25
            case 34: return 33
            case 35: return 27
            case 36: return 23
            case 37: return 44
            default: return 1
            }
        case .Ezra:
            switch chapter {
            case 1: return 11
            case 2: return 70
            case 3: return 13
            case 4: return 24
            case 5: return 17
            case 6: return 22
            case 7: return 28
            case 8: return 36
            case 9: return 15
            case 10: return 44
            default: return 1
            }
        case .Nehemiah:
            switch chapter {
            case 1: return 11
            case 2: return 20
            case 3: return 32
            case 4: return 23
            case 5: return 19
            case 6: return 19
            case 7: return 73
            case 8: return 18
            case 9: return 38
            case 10: return 39
            case 11: return 36
            case 12: return 47
            case 13: return 31
            default: return 1
            }
        case .Esther:
            switch chapter {
            case 1: return 22
            case 2: return 23
            case 3: return 15
            case 4: return 17
            case 5: return 14
            case 6: return 14
            case 7: return 10
            case 8: return 17
            case 9: return 32
            case 10: return 3
            default: return 1
            }
        case .Job:
            switch chapter {
            case 1: return 22
            case 2: return 13
            case 3: return 26
            case 4: return 21
            case 5: return 27
            case 6: return 30
            case 7: return 21
            case 8: return 22
            case 9: return 35
            case 10: return 22
            case 11: return 20
            case 12: return 25
            case 13: return 28
            case 14: return 22
            case 15: return 35
            case 16: return 22
            case 17: return 16
            case 18: return 21
            case 19: return 29
            case 20: return 29
            case 21: return 34
            case 22: return 30
            case 23: return 17
            case 24: return 25
            case 25: return 6
            case 26: return 14
            case 27: return 23
            case 28: return 28
            case 29: return 25
            case 30: return 31
            case 31: return 40
            case 32: return 22
            case 33: return 33
            case 34: return 37
            case 35: return 16
            case 36: return 33
            case 37: return 24
            case 38: return 41
            case 39: return 30
            case 40: return 24
            case 41: return 34
            case 42: return 17
            default: return 1
            }
        case .Psalms:
            switch chapter {
            case 1: return 6
            case 2: return 12
            case 3: return 9
            case 4: return 9
            case 5: return 13
            case 6: return 5
            case 7: return 17
            case 8: return 9
            case 9: return 20
            case 10: return 18
            case 11: return 7
            case 12: return 8
            case 13: return 6
            case 14: return 7
            case 15: return 5
            case 16: return 11
            case 17: return 15
            case 18: return 50
            case 19: return 14
            case 20: return 9
            case 21: return 13
            case 22: return 31
            case 23: return 6
            case 24: return 10
            case 25: return 22
            case 26: return 12
            case 27: return 14
            case 28: return 9
            case 29: return 11
            case 30: return 12
            case 31: return 24
            case 32: return 11
            case 33: return 22
            case 34: return 22
            case 35: return 28
            case 36: return 12
            case 37: return 40
            case 38: return 22
            case 39: return 13
            case 40: return 17
            case 41: return 13
            case 42: return 11
            case 43: return 5
            case 44: return 26
            case 45: return 17
            case 46: return 11
            case 47: return 9
            case 48: return 14
            case 49: return 20
            case 50: return 23
            case 51: return 19
            case 52: return 9
            case 53: return 6
            case 54: return 7
            case 55: return 23
            case 56: return 13
            case 57: return 11
            case 58: return 11
            case 59: return 17
            case 60: return 12
            case 61: return 8
            case 62: return 12
            case 63: return 11
            case 64: return 10
            case 65: return 13
            case 66: return 20
            case 67: return 7
            case 68: return 35
            case 69: return 36
            case 70: return 5
            case 71: return 24
            case 72: return 20
            case 73: return 28
            case 74: return 23
            case 75: return 10
            case 76: return 12
            case 77: return 20
            case 78: return 72
            case 79: return 13
            case 80: return 19
            case 81: return 16
            case 82: return 8
            case 83: return 18
            case 84: return 12
            case 85: return 13
            case 86: return 17
            case 87: return 7
            case 88: return 18
            case 89: return 52
            case 90: return 17
            case 91: return 16
            case 92: return 15
            case 93: return 5
            case 94: return 23
            case 95: return 11
            case 96: return 13
            case 97: return 12
            case 98: return 9
            case 99: return 9
            case 100: return 5
            case 101: return 8
            case 102: return 28
            case 103: return 22
            case 104: return 35
            case 105: return 45
            case 106: return 48
            case 107: return 43
            case 108: return 13
            case 109: return 31
            case 110: return 7
            case 111: return 10
            case 112: return 10
            case 113: return 9
            case 114: return 8
            case 115: return 18
            case 116: return 19
            case 117: return 2
            case 118: return 29
            case 119: return 176
            case 120: return 7
            case 121: return 8
            case 122: return 9
            case 123: return 4
            case 124: return 8
            case 125: return 5
            case 126: return 6
            case 127: return 5
            case 128: return 6
            case 129: return 8
            case 130: return 8
            case 131: return 3
            case 132: return 18
            case 133: return 3
            case 134: return 3
            case 135: return 21
            case 136: return 26
            case 137: return 9
            case 138: return 8
            case 139: return 24
            case 140: return 13
            case 141: return 10
            case 142: return 7
            case 143: return 12
            case 144: return 15
            case 145: return 21
            case 146: return 26
            case 147: return 23
            case 148: return 14
            case 149: return 32
            case 150: return 6
            default: return 1
            }
        case .Proverbs:
            switch chapter {
            case 1: return 33
            case 2: return 22
            case 3: return 35
            case 4: return 27
            case 5: return 23
            case 6: return 35
            case 7: return 27
            case 8: return 36
            case 9: return 18
            case 10: return 32
            case 11: return 31
            case 12: return 28
            case 13: return 25
            case 14: return 35
            case 15: return 33
            case 16: return 33
            case 17: return 28
            case 18: return 24
            case 19: return 29
            case 20: return 30
            case 21: return 31
            case 22: return 29
            case 23: return 35
            case 24: return 34
            case 25: return 28
            case 26: return 28
            case 27: return 27
            case 28: return 28
            case 29: return 27
            case 30: return 33
            case 31: return 31
            default: return 1
            }
        case .Ecclesiastes:
            switch chapter {
            case 1: return 18
            case 2: return 26
            case 3: return 22
            case 4: return 16
            case 5: return 20
            case 6: return 12
            case 7: return 29
            case 8: return 17
            case 9: return 18
            case 10: return 20
            case 11: return 10
            case 12: return 14
            default: return 1
            }
        case .SongOfSolomon:
            switch chapter {
            case 1: return 17
            case 2: return 17
            case 3: return 11
            case 4: return 16
            case 5: return 16
            case 6: return 13
            case 7: return 13
            case 8: return 14
            default: return 1
            }
        case .Isaiah:
            switch chapter {
            case 1: return 31
            case 2: return 22
            case 3: return 26
            case 4: return 6
            case 5: return 30
            case 6: return 13
            case 7: return 25
            case 8: return 22
            case 9: return 21
            case 10: return 34
            case 11: return 16
            case 12: return 6
            case 13: return 22
            case 14: return 32
            case 15: return 9
            case 16: return 14
            case 17: return 14
            case 18: return 7
            case 19: return 25
            case 20: return 6
            case 21: return 17
            case 22: return 25
            case 23: return 18
            case 24: return 23
            case 25: return 12
            case 26: return 21
            case 27: return 13
            case 28: return 29
            case 29: return 24
            case 30: return 33
            case 31: return 9
            case 32: return 20
            case 33: return 24
            case 34: return 17
            case 35: return 10
            case 36: return 22
            case 37: return 38
            case 38: return 22
            case 39: return 8
            case 40: return 31
            case 41: return 29
            case 42: return 25
            case 43: return 28
            case 44: return 28
            case 45: return 25
            case 46: return 13
            case 47: return 15
            case 48: return 22
            case 49: return 26
            case 50: return 11
            case 51: return 23
            case 52: return 15
            case 53: return 12
            case 54: return 17
            case 55: return 13
            case 56: return 12
            case 57: return 21
            case 58: return 14
            case 59: return 21
            case 60: return 22
            case 61: return 11
            case 62: return 12
            case 63: return 19
            case 64: return 12
            case 65: return 25
            case 66: return 24
            default: return 1
            }
        case .Jeremiah:
            switch chapter {
            case 1: return 19
            case 2: return 37
            case 3: return 25
            case 4: return 31
            case 5: return 31
            case 6: return 30
            case 7: return 34
            case 8: return 22
            case 9: return 26
            case 10: return 25
            case 11: return 23
            case 12: return 17
            case 13: return 27
            case 14: return 22
            case 15: return 21
            case 16: return 21
            case 17: return 27
            case 18: return 23
            case 19: return 15
            case 20: return 18
            case 21: return 14
            case 22: return 30
            case 23: return 40
            case 24: return 10
            case 25: return 38
            case 26: return 24
            case 27: return 22
            case 28: return 17
            case 29: return 32
            case 30: return 24
            case 31: return 40
            case 32: return 44
            case 33: return 26
            case 34: return 22
            case 35: return 19
            case 36: return 32
            case 37: return 21
            case 38: return 28
            case 39: return 18
            case 40: return 16
            case 41: return 18
            case 42: return 22
            case 43: return 13
            case 44: return 30
            case 45: return 5
            case 46: return 28
            case 47: return 7
            case 48: return 47
            case 49: return 39
            case 50: return 46
            case 51: return 64
            case 52: return 34
            default: return 1
            }
        case .Lamentations:
            switch chapter {
            case 1: return 22
            case 2: return 22
            case 3: return 66
            case 4: return 22
            case 5: return 22
            default: return 1
            }
        case .Ezekiel:
            switch chapter {
            case 1: return 28
            case 2: return 10
            case 3: return 27
            case 4: return 17
            case 5: return 17
            case 6: return 14
            case 7: return 27
            case 8: return 18
            case 9: return 11
            case 10: return 22
            case 11: return 25
            case 12: return 28
            case 13: return 23
            case 14: return 23
            case 15: return 8
            case 16: return 63
            case 17: return 24
            case 18: return 32
            case 19: return 14
            case 20: return 49
            case 21: return 32
            case 22: return 31
            case 23: return 49
            case 24: return 27
            case 25: return 17
            case 26: return 21
            case 27: return 36
            case 28: return 26
            case 29: return 21
            case 30: return 26
            case 31: return 18
            case 32: return 32
            case 33: return 33
            case 34: return 31
            case 35: return 15
            case 36: return 38
            case 37: return 28
            case 38: return 23
            case 39: return 29
            case 40: return 49
            case 41: return 26
            case 42: return 20
            case 43: return 27
            case 44: return 31
            case 45: return 25
            case 46: return 24
            case 47: return 23
            case 48: return 35
            default: return 1
            }
        case .Daniel:
            switch chapter {
            case 1: return 21
            case 2: return 49
            case 3: return 30
            case 4: return 37
            case 5: return 31
            case 6: return 28
            case 7: return 28
            case 8: return 27
            case 9: return 27
            case 10: return 21
            case 11: return 45
            case 12: return 13
            default: return 1
            }
        case .Hosea:
            switch chapter {
            case 1: return 11
            case 2: return 23
            case 3: return 5
            case 4: return 19
            case 5: return 15
            case 6: return 11
            case 7: return 16
            case 8: return 14
            case 9: return 17
            case 10: return 15
            case 11: return 12
            case 12: return 14
            case 13: return 16
            case 14: return 9
            default: return 1
            }
        case .Joel:
            switch chapter {
            case 1: return 20
            case 2: return 32
            case 3: return 21
            default: return 1
            }
        case .Amos:
            switch chapter {
            case 1: return 15
            case 2: return 16
            case 3: return 15
            case 4: return 13
            case 5: return 27
            case 6: return 14
            case 7: return 17
            case 8: return 14
            case 9: return 15
            default: return 1
            }
        case .Obadiah:
            switch chapter {
            case 1: return 21
            default: return 1
            }
        case .Jonah:
            switch chapter {
            case 1: return 17
            case 2: return 10
            case 3: return 10
            case 4: return 11
            default: return 1
            }
        case .Micah:
            switch chapter {
            case 1: return 16
            case 2: return 13
            case 3: return 12
            case 4: return 13
            case 5: return 15
            case 6: return 16
            case 7: return 20
            default: return 1
            }
        case .Nahum:
            switch chapter {
            case 1: return 15
            case 2: return 13
            case 3: return 19
            default: return 1
            }
        case .Habakkuk:
            switch chapter {
            case 1: return 17
            case 2: return 20
            case 3: return 19
            default: return 1
            }
        case .Zephaniah:
            switch chapter {
            case 1: return 18
            case 2: return 15
            case 3: return 20
            default: return 1
            }
        case .Haggai:
            switch chapter {
            case 1: return 15
            case 2: return 23
            default: return 1
            }
        case .Zechariah:
            switch chapter {
            case 1: return 21
            case 2: return 13
            case 3: return 10
            case 4: return 14
            case 5: return 11
            case 6: return 15
            case 7: return 14
            case 8: return 23
            case 9: return 17
            case 10: return 12
            case 11: return 17
            case 12: return 14
            case 13: return 9
            case 14: return 21
            default: return 1
            }
        case .Malachi:
            switch chapter {
            case 1: return 14
            case 2: return 17
            case 3: return 18
            case 4: return 6
            default: return 1
            }
        case .Matthew:
            switch chapter {
            case 1: return 25
            case 2: return 23
            case 3: return 17
            case 4: return 25
            case 5: return 48
            case 6: return 34
            case 7: return 29
            case 8: return 34
            case 9: return 38
            case 10: return 42
            case 11: return 30
            case 12: return 50
            case 13: return 58
            case 14: return 36
            case 15: return 39
            case 16: return 28
            case 17: return 27
            case 18: return 35
            case 19: return 30
            case 20: return 34
            case 21: return 46
            case 22: return 46
            case 23: return 39
            case 24: return 51
            case 25: return 46
            case 26: return 75
            case 27: return 66
            case 28: return 20
            default: return 1
            }
        case .Mark:
            switch chapter {
            case 1: return 45
            case 2: return 28
            case 3: return 35
            case 4: return 41
            case 5: return 43
            case 6: return 56
            case 7: return 37
            case 8: return 38
            case 9: return 50
            case 10: return 52
            case 11: return 33
            case 12: return 44
            case 13: return 37
            case 14: return 72
            case 15: return 47
            case 16: return 20
            default: return 1
            }
        case .Luke:
            switch chapter {
            case 1: return 80
            case 2: return 52
            case 3: return 38
            case 4: return 44
            case 5: return 39
            case 6: return 49
            case 7: return 50
            case 8: return 56
            case 9: return 62
            case 10: return 42
            case 11: return 54
            case 12: return 59
            case 13: return 35
            case 14: return 35
            case 15: return 32
            case 16: return 31
            case 17: return 37
            case 18: return 43
            case 19: return 48
            case 20: return 47
            case 21: return 38
            case 22: return 71
            case 23: return 56
            case 24: return 53
            default: return 1
            }
        case .John:
            switch chapter {
            case 1: return 51
            case 2: return 25
            case 3: return 36
            case 4: return 54
            case 5: return 47
            case 6: return 71
            case 7: return 53
            case 8: return 59
            case 9: return 41
            case 10: return 42
            case 11: return 57
            case 12: return 50
            case 13: return 38
            case 14: return 31
            case 15: return 27
            case 16: return 33
            case 17: return 26
            case 18: return 40
            case 19: return 42
            case 20: return 31
            case 21: return 25
            default: return 1
            }
        case .Acts:
            switch chapter {
            case 1: return 26
            case 2: return 47
            case 3: return 26
            case 4: return 37
            case 5: return 42
            case 6: return 15
            case 7: return 60
            case 8: return 40
            case 9: return 43
            case 10: return 48
            case 11: return 30
            case 12: return 25
            case 13: return 52
            case 14: return 28
            case 15: return 41
            case 16: return 40
            case 17: return 34
            case 18: return 28
            case 19: return 41
            case 20: return 38
            case 21: return 40
            case 22: return 30
            case 23: return 35
            case 24: return 27
            case 25: return 27
            case 26: return 32
            case 27: return 44
            case 28: return 31
            default: return 1
            }
        case .Romans:
            switch chapter {
            case 1: return 32
            case 2: return 29
            case 3: return 31
            case 4: return 25
            case 5: return 21
            case 6: return 23
            case 7: return 25
            case 8: return 39
            case 9: return 33
            case 10: return 21
            case 11: return 36
            case 12: return 21
            case 13: return 14
            case 14: return 23
            case 15: return 33
            case 16: return 27
            default: return 1
            }
        case .Corinthians1:
            switch chapter {
            case 1: return 31
            case 2: return 16
            case 3: return 23
            case 4: return 21
            case 5: return 13
            case 6: return 20
            case 7: return 40
            case 8: return 13
            case 9: return 27
            case 10: return 33
            case 11: return 34
            case 12: return 31
            case 13: return 13
            case 14: return 40
            case 15: return 58
            case 16: return 24
            default: return 1
            }
        case .Corinthians2:
            switch chapter {
            case 1: return 24
            case 2: return 17
            case 3: return 18
            case 4: return 18
            case 5: return 21
            case 6: return 18
            case 7: return 16
            case 8: return 24
            case 9: return 15
            case 10: return 18
            case 11: return 33
            case 12: return 21
            case 13: return 14
            default: return 1
            }
        case .Galatians:
            switch chapter {
            case 1: return 24
            case 2: return 21
            case 3: return 29
            case 4: return 31
            case 5: return 26
            case 6: return 18
            default: return 1
            }
        case .Ephesians:
            switch chapter {
            case 1: return 23
            case 2: return 22
            case 3: return 21
            case 4: return 32
            case 5: return 33
            case 6: return 24
            default: return 1
            }
        case .Philippians:
            switch chapter {
            case 1: return 30
            case 2: return 30
            case 3: return 21
            case 4: return 23
            default: return 1
            }
        case .Colossians:
            switch chapter {
            case 1: return 29
            case 2: return 23
            case 3: return 25
            case 4: return 18
            default: return 1
            }
        case .Thessalonians1:
            switch chapter {
            case 1: return 10
            case 2: return 20
            case 3: return 13
            case 4: return 18
            case 5: return 28
            default: return 1
            }
        case .Thessalonians2:
            switch chapter {
            case 1: return 12
            case 2: return 17
            case 3: return 18
            default: return 1
            }
        case .Timothy1:
            switch chapter {
            case 1: return 20
            case 2: return 15
            case 3: return 16
            case 4: return 16
            case 5: return 25
            case 6: return 21
            default: return 1
            }
        case .Timothy2:
            switch chapter {
            case 1: return 18
            case 2: return 26
            case 3: return 17
            case 4: return 22
            default: return 1
            }
        case .Titus:
            switch chapter {
            case 1: return 16
            case 2: return 15
            case 3: return 15
            default: return 1
            }
        case .Philemon:
            switch chapter {
            case 1: return 25
            default: return 1
            }
        case .Hebrews:
            switch chapter {
            case 1: return 14
            case 2: return 18
            case 3: return 19
            case 4: return 16
            case 5: return 14
            case 6: return 20
            case 7: return 28
            case 8: return 13
            case 9: return 28
            case 10: return 39
            case 11: return 40
            case 12: return 29
            case 13: return 25
            default: return 1
            }
        case .James:
            switch chapter {
            case 1: return 27
            case 2: return 26
            case 3: return 18
            case 4: return 17
            case 5: return 20
            default: return 1
            }
        case .Peter1:
            switch chapter {
            case 1: return 25
            case 2: return 25
            case 3: return 22
            case 4: return 19
            case 5: return 14
            default: return 1
            }
        case .Peter2:
            switch chapter {
            case 1: return 21
            case 2: return 22
            case 3: return 18
            default: return 1
            }
        case .John1:
            switch chapter {
            case 1: return 10
            case 2: return 29
            case 3: return 24
            case 4: return 21
            case 5: return 21
            default: return 1
            }
        case .John2:
            switch chapter {
            case 1: return 13
            default: return 1
            }
        case .John3:
            switch chapter {
            case 1: return 15
            default: return 1
            }
        case .Jude:
            switch chapter {
            case 1: return 25
            default: return 1
            }
        case .Revelation:
            switch chapter {
            case 1: return 20
            case 2: return 29
            case 3: return 22
            case 4: return 11
            case 5: return 14
            case 6: return 17
            case 7: return 17
            case 8: return 13
            case 9: return 21
            case 10: return 11
            case 11: return 19
            case 12: return 17
            case 13: return 18
            case 14: return 20
            case 15: return 8
            case 16: return 21
            case 17: return 18
            case 18: return 24
            case 19: return 21
            case 20: return 15
            case 21: return 27
            case 22: return 21
            default: return 1
            }
        }
    }

}
